version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      production-dependencies:
        dependency-type: 'production'
        patterns:
          - '*'
      development-dependencies:
        dependency-type: 'development'
        patterns:
          - '*'
    ignore:
      # For all packages, ignore major updates
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

